"use client";

import { useState, useEffect, useCallback, useMemo, useSyncExternalStore } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import Link from "next/link";
import { UrlCheckForm } from "@/components/url-check-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { CheckReport } from "@/lib/check-indicators";

type HistoryEntry = {
  url: string;
  totalScore: number;
  maxScore: number;
  grade: string;
  checkedAt: string;
};

const HISTORY_KEY = "aicheck-history";
const MAX_HISTORY = 20;

function getHistory(): HistoryEntry[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(HISTORY_KEY) ?? "[]");
  } catch {
    return [];
  }
}

function saveToHistory(report: CheckReport) {
  const history = getHistory();
  const entry: HistoryEntry = {
    url: report.url,
    totalScore: report.totalScore,
    maxScore: report.maxScore,
    grade: report.grade,
    checkedAt: report.checkedAt,
  };
  const filtered = history.filter((h) => h.url !== entry.url);
  filtered.unshift(entry);
  localStorage.setItem(HISTORY_KEY, JSON.stringify(filtered.slice(0, MAX_HISTORY)));
}

function ScoreCircle({ score, maxScore, grade }: { score: number; maxScore: number; grade: string }) {
  const pct = Math.round((score / maxScore) * 100);
  const gradeColors: Record<string, string> = {
    A: "text-green-400",
    B: "text-blue-400",
    C: "text-yellow-400",
    D: "text-orange-400",
    F: "text-red-400",
  };
  const strokeColors: Record<string, string> = {
    A: "#4ade80",
    B: "#60a5fa",
    C: "#facc15",
    D: "#fb923c",
    F: "#f87171",
  };

  const radius = 56;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (pct / 100) * circumference;

  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative flex h-36 w-36 items-center justify-center">
        <svg className="absolute -rotate-90" width="144" height="144" viewBox="0 0 144 144" role="img" aria-label={`スコア: ${grade}ランク ${pct}/100`}>
          <circle cx="72" cy="72" r={radius} fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="8" />
          <circle
            cx="72" cy="72" r={radius} fill="none"
            stroke={strokeColors[grade] ?? "#fff"}
            strokeWidth="8"
            strokeLinecap="round"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            style={{ transition: "stroke-dashoffset 1s ease-out" }}
          />
        </svg>
        <div className="text-center">
          <span className={`text-4xl font-bold ${gradeColors[grade] ?? "text-white"}`}>{grade}</span>
          <div className="text-sm text-white/50">{pct}/100</div>
        </div>
      </div>
    </div>
  );
}

function StatusBadge({ status }: { status: "pass" | "warn" | "fail" }) {
  const variants: Record<string, { label: string; cls: string }> = {
    pass: { label: "OK", cls: "bg-green-500/20 text-green-400 border-green-500/30" },
    warn: { label: "警告", cls: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30" },
    fail: { label: "要対応", cls: "bg-red-500/20 text-red-400 border-red-500/30" },
  };
  const v = variants[status];
  return <Badge className={`${v.cls} border`}>{v.label}</Badge>;
}

function generateReportText(report: CheckReport): string {
  const pct = Math.round((report.totalScore / report.maxScore) * 100);
  const lines = [
    `AI Check - GEOスコアレポート`,
    `================================`,
    `URL: ${report.url}`,
    `スコア: ${pct}/100 (グレード: ${report.grade})`,
    `チェック日時: ${new Date(report.checkedAt).toLocaleString("ja-JP")}`,
    ``,
    `--- 詳細結果 ---`,
  ];

  for (const r of report.results) {
    const icon = r.status === "pass" ? "[OK]" : r.status === "warn" ? "[!]" : "[X]";
    lines.push(`${icon} ${r.message} (${r.score}/${r.maxScore})`);
    if (r.details) lines.push(`    ${r.details}`);
  }

  const failItems = report.results.filter((r) => r.status === "fail");
  const warnItems = report.results.filter((r) => r.status === "warn");

  if (failItems.length > 0 || warnItems.length > 0) {
    lines.push("");
    lines.push("--- 改善アクション ---");
    for (const item of [...failItems, ...warnItems]) {
      lines.push(`- ${item.message}`);
    }
  }

  lines.push("");
  lines.push("Generated by AI Check (https://ai-check.ezoai.jp)");

  return lines.join("\n");
}

function PriorityActions({ report }: { report: CheckReport }) {
  const actionItems = report.results
    .filter((r) => r.status === "fail" || r.status === "warn")
    .sort((a, b) => (b.maxScore - b.score) - (a.maxScore - a.score));

  if (actionItems.length === 0) {
    return (
      <div className="rounded-lg border border-green-500/20 bg-green-500/5 p-6 text-center">
        <p className="text-lg font-semibold text-green-400">全項目クリア</p>
        <p className="mt-1 text-sm text-white/50">
          あなたのサイトはAI検索に十分対応しています。
        </p>
      </div>
    );
  }

  const generatorMap: Record<string, { path: string; name: string }> = {
    "robots-txt": { path: "/generate/robots-txt", name: "robots.txt生成ツール" },
    "llms-txt": { path: "/generate/llms-txt", name: "llms.txt生成ツール" },
    "structured-data": { path: "/generate/json-ld", name: "JSON-LD生成ツール" },
  };

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold text-white">改善アクション</h2>
      <p className="text-sm text-white/50">
        影響度の高い順に改善することをおすすめします。
      </p>
      <div className="space-y-3">
        {actionItems.map((item, i) => {
          const potential = item.maxScore - item.score;
          const gen = generatorMap[item.id];
          return (
            <div
              key={item.id}
              className="flex items-start gap-4 rounded-lg border border-white/10 bg-white/5 p-4"
            >
              <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${
                item.status === "fail" ? "bg-red-500/20 text-red-400" : "bg-yellow-500/20 text-yellow-400"
              }`}>
                {i + 1}
              </span>
              <div className="flex-1">
                <p className="text-sm font-medium text-white">{item.message}</p>
                <p className="mt-0.5 text-xs text-white/40">+{potential}pt 改善可能</p>
                {gen && (
                  <Link
                    href={gen.path}
                    className="mt-2 inline-block cursor-pointer text-xs text-primary/80 transition-all duration-200 hover:text-primary"
                  >
                    {gen.name}で修正 →
                  </Link>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

const emptyHistory: HistoryEntry[] = [];

function subscribeStorage(cb: () => void) {
  window.addEventListener("storage", cb);
  return () => window.removeEventListener("storage", cb);
}

function CheckHistory({ currentUrl }: { currentUrl: string }) {
  const allHistory = useSyncExternalStore(subscribeStorage, getHistory, () => emptyHistory);

  const history = useMemo(
    () => allHistory.filter((h) => h.url !== currentUrl),
    [allHistory, currentUrl]
  );

  if (history.length === 0) return null;

  const gradeColors: Record<string, string> = {
    A: "text-green-400",
    B: "text-blue-400",
    C: "text-yellow-400",
    D: "text-orange-400",
    F: "text-red-400",
  };

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold text-white">チェック履歴</h2>
      <div className="space-y-2">
        {history.slice(0, 5).map((entry) => (
          <Link
            key={`${entry.url}-${entry.checkedAt}`}
            href={`/check?url=${encodeURIComponent(entry.url)}`}
            className="flex cursor-pointer items-center justify-between rounded-lg border border-white/10 bg-white/5 p-4 transition-all duration-200 hover:border-white/20"
          >
            <div className="min-w-0 flex-1">
              <p className="truncate text-sm text-white/70">{entry.url}</p>
              <p className="text-xs text-white/30">
                {new Date(entry.checkedAt).toLocaleDateString("ja-JP")}
              </p>
            </div>
            <div className="ml-4 text-right">
              <span className={`text-lg font-bold ${gradeColors[entry.grade] ?? "text-white"}`}>
                {entry.grade}
              </span>
              <p className="text-xs text-white/30">
                {Math.round((entry.totalScore / entry.maxScore) * 100)}/100
              </p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

const indicatorTips: Record<string, { tip: string; guide?: string }> = {
  "robots-txt": {
    tip: "robots.txtでGPTBot, ClaudeBot, PerplexityBot等を明示的にAllowに設定しましょう。",
    guide: "/generate/robots-txt",
  },
  "llms-txt": {
    tip: "サイト概要・主要ページ・API情報をまとめたllms.txtを設置しましょう。",
    guide: "/generate/llms-txt",
  },
  "structured-data": {
    tip: "業界に合ったJSON-LD構造化データを設置しましょう。Product, Article, FAQPage等が有効です。",
    guide: "/generate/json-ld",
  },
  "meta-tags": {
    tip: "title, meta description, OGPタグ、canonical URL、lang属性を全ページに設定しましょう。",
  },
  "content-structure": {
    tip: "h1, main, nav, article, section等のセマンティックHTMLタグで文書構造を明確にしましょう。",
  },
  "ssr": {
    tip: "サーバーサイドレンダリング（SSR/SSG）を使用し、HTMLにコンテンツを含めましょう。",
  },
  "sitemap": {
    tip: "全主要ページを含むsitemap.xmlを設置し、robots.txtからリンクしましょう。",
  },
};

export function CheckPageClient() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const url = searchParams.get("url") ?? "";
  const [report, setReport] = useState<CheckReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [urlCopied, setUrlCopied] = useState(false);
  const [recheckKey, setRecheckKey] = useState(0);

  useEffect(() => {
    if (!url) return;
    let cancelled = false;

    const runCheck = async () => {
      try {
        const res = await fetch("/api/check", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url }),
        });
        const data = await res.json();
        if (cancelled) return;
        if (data.error) {
          setError(data.error);
        } else {
          setReport(data);
          saveToHistory(data);
        }
      } catch {
        if (!cancelled) setError("チェック中にエラーが発生しました。");
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    setReport(null);
    setError("");
    setLoading(true);
    runCheck();

    return () => { cancelled = true; };
  }, [url, recheckKey]);

  const handleRecheck = useCallback(() => {
    if (!url || loading) return;
    setRecheckKey((k) => k + 1);
  }, [url, loading]);

  const handleCopyReport = useCallback(() => {
    if (!report) return;
    navigator.clipboard.writeText(generateReportText(report));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [report]);

  const handleDownloadReport = useCallback(() => {
    if (!report) return;
    const text = generateReportText(report);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const blobUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = blobUrl;
    a.download = `ai-check-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(blobUrl);
  }, [report]);

  const handleShareX = useCallback(() => {
    if (!report) return;
    const pct = Math.round((report.totalScore / report.maxScore) * 100);
    const text = `AI検索対応度チェック結果: ${report.grade}ランク (${pct}/100)\n${report.url}\n\n#GEO対策 #AI検索`;
    const shareUrl = `https://ai-check.ezoai.jp/check?url=${encodeURIComponent(report.url)}`;
    window.open(
      `https://x.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(shareUrl)}`,
      "_blank",
      "noopener,noreferrer"
    );
  }, [report]);

  const handleCopyShareUrl = useCallback(() => {
    if (!report) return;
    const shareUrl = `https://ai-check.ezoai.jp/check?url=${encodeURIComponent(report.url)}`;
    navigator.clipboard.writeText(shareUrl);
    setUrlCopied(true);
    setTimeout(() => setUrlCopied(false), 2000);
  }, [report]);

  return (
    <div className="py-16">
      <h1 className="mb-8 text-center text-3xl font-bold text-white">
        GEOスコアチェック
      </h1>

      <div className="mx-auto mb-12 max-w-xl">
        <UrlCheckForm size="sm" />
      </div>

      {loading && (
        <div className="py-16 text-center" role="status" aria-live="polite">
          <div className="mx-auto mb-6 h-12 w-12 animate-spin rounded-full border-2 border-white/10 border-t-white/70" />
          <div className="mb-2 text-lg text-white/70">チェック中...</div>
          <p className="text-sm text-white/40">{url} を分析しています</p>
          <div className="mx-auto mt-6 max-w-xs space-y-3">
            {["robots.txt", "llms.txt", "HTML構造", "メタデータ", "サイトマップ"].map((item) => (
              <div key={item} className="flex items-center gap-3 text-sm text-white/30">
                <div className="h-1.5 w-1.5 animate-pulse rounded-full bg-white/30" />
                {item} を確認中
              </div>
            ))}
          </div>
        </div>
      )}

      {error && (
        <div role="alert" className="mx-auto max-w-xl rounded-lg border border-red-500/30 bg-red-500/10 p-6 text-center">
          <p className="text-red-400">{error}</p>
          <p className="mt-2 text-sm text-white/40">URLを確認して再度お試しください。</p>
        </div>
      )}

      {report && (
        <div className="space-y-8">
          <div className="text-center">
            <p className="mb-4 text-sm text-white/50">{report.url}</p>
            <ScoreCircle
              score={report.totalScore}
              maxScore={report.maxScore}
              grade={report.grade}
            />
            <p className="mt-2 text-sm text-white/40">
              チェック日時: {new Date(report.checkedAt).toLocaleString("ja-JP")}
            </p>
            <div className="mt-4 flex flex-wrap justify-center gap-3">
              <Button
                variant="outline"
                size="sm"
                className="cursor-pointer border-white/10 bg-white/5 text-white/70 transition-all duration-200 hover:bg-white/10 hover:text-white"
                onClick={handleCopyReport}
              >
                {copied ? "コピーしました" : "レポートをコピー"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="cursor-pointer border-white/10 bg-white/5 text-white/70 transition-all duration-200 hover:bg-white/10 hover:text-white"
                onClick={handleDownloadReport}
              >
                テキストで保存
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="cursor-pointer border-white/10 bg-white/5 text-white/70 transition-all duration-200 hover:bg-white/10 hover:text-white"
                onClick={handleShareX}
              >
                Xでシェア
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="cursor-pointer border-white/10 bg-white/5 text-white/70 transition-all duration-200 hover:bg-white/10 hover:text-white"
                onClick={handleCopyShareUrl}
              >
                {urlCopied ? "URLコピー済み" : "URLをコピー"}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="cursor-pointer border-primary/30 bg-primary/10 text-primary transition-all duration-200 hover:bg-primary/20"
                onClick={handleRecheck}
              >
                再チェック
              </Button>
            </div>
          </div>

          <CheckHistory currentUrl={report.url} />

          <PriorityActions report={report} />

          <div className="space-y-4">
            <h2 className="text-xl font-bold text-white">詳細結果</h2>
            {report.results.map((r) => (
              <div
                key={r.id}
                className="rounded-lg border border-white/10 bg-white/5 p-6"
              >
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="font-semibold text-white">{r.message}</h3>
                  <StatusBadge status={r.status} />
                </div>
                {r.details && (
                  <p className="mb-3 text-sm leading-relaxed text-white/50">
                    {r.details}
                  </p>
                )}
                {r.code && (
                  <pre className="overflow-x-auto rounded-lg bg-black/50 p-4 text-xs text-white/70">
                    <code>{r.code}</code>
                  </pre>
                )}
                <div className="mt-3 flex items-center gap-3">
                  <div className="h-1.5 flex-1 rounded-full bg-white/10">
                    <div
                      className="h-1.5 rounded-full transition-all duration-500"
                      style={{
                        width: `${(r.score / r.maxScore) * 100}%`,
                        backgroundColor: r.status === "pass" ? "#4ade80" : r.status === "warn" ? "#facc15" : "#f87171",
                      }}
                    />
                  </div>
                  <span className="text-xs text-white/30">{r.score}/{r.maxScore}</span>
                </div>
                {r.status !== "pass" && indicatorTips[r.id] && (
                  <div className="mt-3 rounded border border-primary/10 bg-primary/5 px-4 py-2.5">
                    <p className="text-xs leading-relaxed text-primary/80">
                      {indicatorTips[r.id].tip}
                    </p>
                    {indicatorTips[r.id].guide && (
                      <Link
                        href={indicatorTips[r.id].guide!}
                        className="mt-1 inline-block cursor-pointer text-xs text-primary/60 transition-all duration-200 hover:text-primary"
                      >
                        ツールで修正 →
                      </Link>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {!url && !loading && (
        <div className="space-y-12">
          <div className="py-16 text-center text-white/40">
            <p className="text-lg">上のフォームにURLを入力してチェックを開始</p>
            <Link
              href="/check/compare"
              className="mt-4 inline-block cursor-pointer text-sm text-primary/70 transition-all duration-200 hover:text-primary"
            >
              複数サイトを比較する →
            </Link>
          </div>
          <CheckHistory currentUrl="" />
        </div>
      )}
    </div>
  );
}
