"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const AI_CRAWLERS = [
  { id: "GPTBot", name: "GPTBot (ChatGPT)", default: true },
  { id: "ChatGPT-User", name: "ChatGPT-User (ChatGPT Browse)", default: true },
  { id: "ClaudeBot", name: "ClaudeBot (Claude)", default: true },
  { id: "anthropic-ai", name: "anthropic-ai (Anthropic)", default: true },
  { id: "PerplexityBot", name: "PerplexityBot (Perplexity)", default: true },
  { id: "Google-Extended", name: "Google-Extended (Gemini)", default: true },
  { id: "Amazonbot", name: "Amazonbot (Alexa)", default: true },
  { id: "Applebot-Extended", name: "Applebot-Extended (Apple AI)", default: true },
  { id: "cohere-ai", name: "Cohere AI", default: true },
  { id: "Bytespider", name: "Bytespider (TikTok)", default: false },
  { id: "CCBot", name: "CCBot (Common Crawl)", default: false },
];

export function RobotsTxtGenerator() {
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [allowedCrawlers, setAllowedCrawlers] = useState<string[]>(
    AI_CRAWLERS.filter((c) => c.default).map((c) => c.id)
  );
  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);

  function toggleCrawler(id: string) {
    setAllowedCrawlers((prev) =>
      prev.includes(id) ? prev.filter((c) => c !== id) : [...prev, id]
    );
  }

  function generate() {
    const lines: string[] = [];
    lines.push("# robots.txt - AIクローラー対応");
    lines.push("# Generated by AI Check (https://ai-check.ezoai.jp)");
    lines.push("");
    lines.push("User-agent: *");
    lines.push("Allow: /");
    lines.push("");

    allowedCrawlers.forEach((c) => {
      lines.push(`User-agent: ${c}`);
      lines.push("Allow: /");
      lines.push("");
    });

    const blocked = AI_CRAWLERS.filter((c) => !allowedCrawlers.includes(c.id));
    if (blocked.length > 0) {
      lines.push("# Blocked AI crawlers");
      blocked.forEach((c) => {
        lines.push(`User-agent: ${c.id}`);
        lines.push("Disallow: /");
        lines.push("");
      });
    }

    if (sitemapUrl.trim()) {
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    setOutput(lines.join("\n"));
  }

  function handleCopy() {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  }

  function handleDownload() {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="grid gap-8 lg:grid-cols-2">
      <div className="space-y-4">
        <div>
          <Label htmlFor="robots-sitemap-url" className="mb-1.5 text-white/70">サイトマップURL（任意）</Label>
          <Input
            id="robots-sitemap-url"
            value={sitemapUrl}
            onChange={(e) => setSitemapUrl(e.target.value)}
            placeholder="https://example.com/sitemap.xml"
            maxLength={2048}
            className="border-white/10 bg-white/5 text-white placeholder:text-white/30"
          />
        </div>
        <div>
          <Label className="mb-3 text-white/70">AIクローラー設定</Label>
          <div className="space-y-2">
            {AI_CRAWLERS.map((crawler) => (
              <label
                key={crawler.id}
                className="flex cursor-pointer items-center gap-3 rounded-lg border border-white/10 bg-white/5 p-3 transition-all duration-200 hover:border-white/20"
              >
                <input
                  type="checkbox"
                  checked={allowedCrawlers.includes(crawler.id)}
                  onChange={() => toggleCrawler(crawler.id)}
                  className="h-4 w-4 accent-primary"
                />
                <span className="text-sm text-white/70">{crawler.name}</span>
              </label>
            ))}
          </div>
        </div>
        <Button
          onClick={generate}
          className="w-full cursor-pointer bg-primary text-primary-foreground transition-all duration-200 hover:bg-primary/80"
        >
          生成
        </Button>
      </div>
      <div>
        {output ? (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-white">生成結果</span>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleCopy}
                  className="cursor-pointer border-white/10 text-white/70 transition-all duration-200 hover:text-white"
                >
                  {copied ? "コピー済み" : "コピー"}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleDownload}
                  className="cursor-pointer border-white/10 text-white/70 transition-all duration-200 hover:text-white"
                >
                  ダウンロード
                </Button>
              </div>
            </div>
            <pre className="overflow-x-auto rounded-lg border border-white/10 bg-white/5 p-4 text-sm leading-relaxed text-white/70">
              <code>{output}</code>
            </pre>
          </div>
        ) : (
          <div className="flex h-full items-center justify-center rounded-lg border border-dashed border-white/10 p-8">
            <p className="text-center text-sm text-white/30">
              クローラーを選択して
              <br />
              「生成」をクリック
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
